### ISSUE TITLE
Any chance to submit this as unoficial app to LG store?

### ISSUE THREAD

**Issue by tamodolo** [mateussouzaweb/crunchyroll-webos#1]
I read that it's free to add apps there.

**Comment by tamodolo** [comment]
Also, the webapp have some white bars at the botton and right of screen. This is a problem for OLED panels.

**Comment by mateussouzaweb** [comment]
Sorry man, we can't publish this project to the LG store.

**Comment by themakshter** [comment]
> Sorry man, we can't publish this project to the LG store.

Hello, any chance you could explain your reasons? Just curious to hear about it since we can say that it is an un-official one
