### ISSUE TITLE
Publishing on webOS Homebrew Channel

### ISSUE THREAD

**Issue by Informatic** [mateussouzaweb/crunchyroll-webos#11]
Hello!
This seems like a great project. A couple of quick questions.

1. I don't see any license stated. What is the license of this project?

2. [webosbrew](https://webosbrew.org) (that I am part of) maintains [a repository of unofficial webOS apps](https://repo.webosbrew.org) - would you mind if we published Your application there?
Currently distribution is based on links to "manifest files" that are (mostly) included in github releases, alongside `ipk` files, like here for example: https://github.com/mariotaku/moonlight-tv/releases/tag/v1.2.7 ([manifest schema](https://github.com/webosbrew/docs/blob/main/schemas/HomebrewPackageManifest.schema.json), [apps repository](https://github.com/webosbrew/apps-repo), [final static site](https://repo.webosbrew.org/))
I can help you with setting up full CI flow to automatically build webOS-side application and generate relevant manifest when pushing a tag into the repo, to reduce any effort on You. Example nodejs-based CI setup we have in one of the projects: https://github.com/webosbrew/youtube-webos/blob/main/.github/workflows/release.yml

3. Also, possibly a useful hint: npm package [`@webosose/ares-cli`](https://www.npmjs.com/package/@webosose/ares-cli) is pretty much a fully-featured minimal SDK (compatible with webOS TV) tooling set that can be installed via npm - works same as original SDK but doesn't pollute `/opt` or any other system paths, and is fairly easy to use in CI.

**Comment by mateussouzaweb** [comment]
@Informatic 

1.  License added to the project.
2.  Would be very nice see this project on the webosbrew. I already was planning to publish my app on the webosbrew in the future... the contribution of @mariotaku make it very easier now. 
3. Good information! I personally don't have the SDK installed here, but will update the instructions to use that package. Thanks.

**Comment by Informatic** [comment]
Oh, I didn't notice @mariotaku started working on it :D 
We can probably consider this issue solved now.
