### ISSUE TITLE
Doesn’t properly load episode

### ISSUE THREAD

**Issue by Evilryu1068** [mateussouzaweb/crunchyroll-webos#16]
When I try to select the next episode it would load the wrong one,  for example from episode 4 to 7. Also I can't seem to select the icons using the remote controller to pick a show, the magic remote feature works though.

**Comment by mateussouzaweb** [comment]
Can you provide the serie and episode number for testing? I am pretty sure that is fixed with version 1.6.0, but maybe it is not working on all serie...

**Comment by Evilryu1068** [comment]
Mob Psycho 100, Episode 4 skips to Episode 8. Another example is Re:
Zero-Starting Life in Another World, episode 1 skips to 5.

**Comment by drcorg** [comment]
I'm getting the same problem, Episode 1 of Detective Conan skips to episode 5. Additionally, the directional buttons stopped working on my magic remote on the latest update.

**Comment by Timwun** [comment]
Can confirm this behaviour.

**Comment by mateussouzaweb** [comment]
After trying a few variations, I came to the best-case scenario based on what we can grab from the API. The next and previous episode navigation should work as expected now, but unfortunately, the next and previous episode will not work between seasons, it's a limitation of the API...

Can you please test if this is ok with version 1.8.0?

**Comment by Timwun** [comment]
I will try that out tomorrow

**Comment by Timwun** [comment]
It does work perfectly fine. :) 

I would say close this issue!

Thanks a lot!

**Comment by Evilryu1068** [comment]
Yes, I also tested it and the issue is fixed. Thanks so much!

**Comment by mateussouzaweb** [comment]
Nice!
