### ISSUE TITLE
Navigation 

### ISSUE THREAD

**Issue by Pizyman** [mateussouzaweb/crunchyroll-webos#17]
Can't navigate video selection with remote. Only allows me to select queue, history, and popular. No up and down navigation, no search bar or anything.

**Comment by Fasox** [comment]
Same happened to me with the latest update.

**Comment by Fasox** [comment]
Just tested it , going back to 1.5.4 solves the problem.

**Comment by mateussouzaweb** [comment]
Thanks for the report, I am working on another rewrite for this project to use more modern code. Once I solve the issues with the compiler, the new version will be published to fix these issues.

**Comment by mateussouzaweb** [comment]
@Fasox @Pizyman I just released the version 1.8.0 with full revision on keyboard navigation. Can you please test this version?

**Comment by joaopedrosgs** [comment]
I can confirm that the navigation is working now. However, thumbnails don't seem to load

**Comment by arbarbosa1979** [comment]
I was able to navigate normally using the remote control, but I could not select the video resolution, even clicking ok, the resolution was not changed, it remained in auto.

**Comment by mateussouzaweb** [comment]
Nice, I will close this issue and see if I can do something else on the video resolution (https://github.com/mateussouzaweb/crunchyroll-webos/issues/2). It works on PC, but on the TV it does not, maybe it is related to the chromium version without proper support....
