### ISSUE TITLE
Blank Brown Screen on Startup on OLED55C7V-Z

### ISSUE THREAD

**Issue by richardpodkolinski** [mateussouzaweb/crunchyroll-webos#18]
Hi, perhaps you might be able to help me.

I tried installing the application several times on an OLED55C7V-Z with WebOS 3.9.0-62709 (dreadlocks2-dudhwa).

I have attempted the Homebrew app version, as well as the LG Developer mode version.

I have also tried several versions back, from 1.8.0 all the way to 1.5.1.

In every case, I appear to be getting just a brown static screen. [No movement. I've attached this very uninformative image if that helps.](https://imgur.com/a/eehIvl4) 

The VS Code plugin informs me that the application is running, but nothing seems to be happening on the screen.

Any ideas on what might be going wrong here and how I might be able to remedy it?

Thanks for all the hard work btw.

**Comment by mateussouzaweb** [comment]
This is very likely because your WebOS version is old and script errors are happening... The app is compatible only with WebOS 4.X or more recent.

Are you able to use the ``npm run app-launch`` and ``npm run app-inspect`` then get the console error in the browser? This will require a bit of web development knowledge if you have any...

**Comment by joaopauloap** [comment]
Oi Mateus, falei com você pelo e-mail. Acho que por aqui é melhor de dialogar. 
![image](https://user-images.githubusercontent.com/36867356/181863431-15f6e501-7d1c-4090-a677-4b2495e95d5f.png)

**Comment by mateussouzaweb** [comment]
@joaopauloap você agora só precisa usar o comando de inspect e abrir o devtools no navegador:

- Com o app instalado na TV, execute no terminal do PC: ``ares-inspect --app com.crunchyroll.webos --host-port 9222`` 
- Abrar o Chrome em ``chrome://inspect/#devices`` (https://wd.imgix.net/image/BrQidfK9jaQyIHwdw91aVpkPiib2/4P4G0Hmt3CbDkqMoTOiY.png?auto=format&w=964) e adicione a porta/IP que aparece no console. 
- O app deve aparecer na lista e ai é só clicar em ``inspect`` para abrir o DevTools do App.
- Para finalizar vá até a aba Console do DevTools e reporte os erros que aparecem.

**Comment by joaopauloap** [comment]
![image](https://user-images.githubusercontent.com/36867356/182228329-0ad29c66-b798-4e95-9258-f8c9d65f5f28.png)

**Comment by mateussouzaweb** [comment]
@joaopauloap consegui utilizar o Chrome 38 e publiquei uma nova versão com correções. Pode ver se ela funciona mesmo que não seja perfeita?

**Comment by joaopauloap** [comment]
Oi Mateus, eu instalei o app pelo homebrew, mas lá ainda está com a release 1.9.1. Não consegui instalar com aquele método para desenvolvedores. Vou continuar tentando aqui

**Comment by joaopauloap** [comment]
Vou mostrar tudo o que apareceu aqui e detalhar os acontecimentos. Primeiramente agora o formulário de login apareceu:
![image](https://user-images.githubusercontent.com/36867356/182459410-0e7053fb-103e-48f9-9d97-adb4302bec48.png)

Ao preencher o formulario e logar ai apareceu o menu lateral porém continuou com o formulario de login na tela e o app travou:
![image](https://user-images.githubusercontent.com/36867356/182460212-83f0ad62-da72-481a-b0f0-4097391ef92e.png)

Reiniciei a tv e abri o app. Agora o formulario de login sumiu e ja abriu na opção queue, mostrando o ultimo anime que assisti, sendo possível assisti-lo tranquilamente ao seleciona-lo:
![image](https://user-images.githubusercontent.com/36867356/182460886-2b70c088-3db0-46f9-9285-626d129097ef.png)

O app funciona normalmente enquanto estiver selecionando entre os botões queue, history e logout, porem ao selecionar a opção do catalogo de Animes o app trava, tendo que reiniciar novamente:
![image](https://user-images.githubusercontent.com/36867356/182461160-e9bf1a8c-d3f2-4fa8-873e-34291f5ff714.png)

**Comment by mateussouzaweb** [comment]
@joaopauloap publiquei mais uma versão com novas correções focando o WebOS 3.x. Você pode testar mais uma vez?

**Comment by joaopauloap** [comment]
Os mesmos 4 warnings ainda aparecem no console, mas depois dessa release 1.9.3 o app ficou bom, está tudo funcionando e o app não trava mais. Muito obrigado pela atenção, Mateus, você merece muito reconhecimento. Estou seguindo o repositório. Tenta mostrar esse projeto pra crunchyroll, acho que você consegue fácil um cargo como dev lá. Eles estão procurando.
