### ISSUE TITLE
Black screen after upgrading to v1.9.0

### ISSUE THREAD

**Issue by Timwun** [mateussouzaweb/crunchyroll-webos#19]
Hey,

After the latest release the app stopped working for me.
When I start the app it stays black and nothing happens. 
v1.8.0 does still work fine. Maybe some dependency you updated is incompatible?

**Comment by mateussouzaweb** [comment]
Check version 1.9.1, the issue should be fixed.

**Comment by Timwun** [comment]
It's fixed! Thanks!!!
