### ISSUE TITLE
No streams to load

### ISSUE THREAD

**Issue by SolracLeinad** [mateussouzaweb/crunchyroll-webos#21]
Today a new simulcast episode came out, I tried to play it but I got an "No streams to load." error underneath the episode title.

I turned my TV off to close the app but I keep getting the same result.
![tv](https://user-images.githubusercontent.com/23008975/192078045-15f4109c-6115-41e3-8abc-d9ead1bc061f.jpeg)

**Comment by Ca-im** [comment]
I'm also having this issue, but only when I select to stream in any audio that isn't Japanese

**Comment by mateussouzaweb** [comment]
@SolracLeinad @Ca-im can you check if the error persists? If yes, please give the episode details for debugging...

**Comment by mateussouzaweb** [comment]
I will close this issue because is duplicated - see #33
