### ISSUE TITLE
Media error: trying recovery...

### ISSUE THREAD

**Issue by SolracLeinad** [mateussouzaweb/crunchyroll-webos#22]
So I can watch 1 or maybe 3 episodes of any anime without any issue but at some point, the next thing I play will yield "Media error: trying recovery..."
Once I get this error every episode of every series will yield the same error until I turn my TV off and on again.
![tv](https://user-images.githubusercontent.com/23008975/193902493-316e49a9-24f9-4e9a-aa22-0a765702f3ca.jpeg)

This happens all the time.

My TV is NOT rooted btw.

**Comment by joaopauloap** [comment]
this is happening with me too. try this: dont next episode until the episode really end.

ps: if the bug still happens you don't need to turn off the tv, you can just close the tv app like we do on mobile. on my tv lg webos has this functionality. so when you open the app again it will go back to normal.

**Comment by SolracLeinad** [comment]
> ps: if the bug still happens you don't need to turn off the tv, you can just close the tv app like we do on mobile. on my tv lg webos has this functionality. so when you open the app again it will go back to normal.

Unfortunately my TV lacks of that functionality. I can only open other apps and hope for the garbage collector (or something like that) to fire up by itself and decide to close the app for me.

The fastest way is to turn the TV off and on again. 

I'm on WebOS 04.40.08

**Comment by mohfathy0** [comment]
> > ps: if the bug still happens you don't need to turn off the tv, you can just close the tv app like we do on mobile. on my tv lg webos has this functionality. so when you open the app again it will go back to normal.
> 
> Unfortunately my TV lacks of that functionality. I can only open other apps and hope for the garbage collector (or something like that) to fire up by itself and decide to close the app for me.
> 
> The fastest way is to turn the TV off and on again.
> 
> I'm on WebOS 04.40.08

I believe you should be able to close the app when you go to recent apps there is a close button on top of the preview of reach recent app once you hover over it or maybe just put to fucus on it if you are not using magic remote 
sadly I am still experiencing the same issue till today but the workaround to wait or skip ahead to the last second and let it end works

**Comment by mateussouzaweb** [comment]
Please update the app and try again... I will close this issue for now, feel free to open it again if errors persist.
