### ISSUE TITLE
Missing content compared to the official CR app & browser version

### ISSUE THREAD

**Issue by HealsCodes** [mateussouzaweb/crunchyroll-webos#23]
It appears that in the series list, search, as well as your watch list certain content isn't shown.
I only noticed this recently and have had no other issues with your app on my TV.

One example for me is One Piece which CR recently added in full (all 10+ seasons).
I can find it in the web version and on any of the official apps, can add it to my watchlist and watch it.
However it is completely absent in your app even after adding it on my list from elsewhere.

I'm using the app logged in with a Premium account, watching from Germany.

**Comment by mateussouzaweb** [comment]
The new app version should fix this issue automatically since we are using the new up to date API. Please update the app and try again.
