### ISSUE TITLE
Create for tizen? 

### ISSUE THREAD

**Issue by Nexow91** [mateussouzaweb/crunchyroll-webos#27]
Hello sorry to write my request as a problem i am new to github and unfortunately don't know how or where to post requests yet so please bear with me. Is there any way to make a crunchyroll app fir tizen samsung has also a sdk and the tizen studio for app development. That would be really great as I have been looking for months and am getting desperate. 

I look forward to hearing from you.

**Comment by mateussouzaweb** [comment]
There is a tizen app here: https://github.com/jhassan8/crunchyroll-tizen
