### ISSUE TITLE
tizenOS

### ISSUE THREAD

**Issue by iqsilva** [mateussouzaweb/crunchyroll-webos#3]
Hi friend, are you going develop to tizenOS too or not?

**Comment by mateussouzaweb** [comment]
Hi Igor,

Did you tried to access the project from the website included on Readme?
If the player won't work at your TV Browser, is very unlikely that an Tizen
OS app work too as they will use the same tech...

**Comment by iqsilva** [comment]
Mateus, I have tested in Samsung TV and it works fine with the browser! Thanks man
