### ISSUE TITLE
[bug] App won't create session

### ISSUE THREAD

**Issue by Narcwis** [mateussouzaweb/crunchyroll-webos#31]
App fails to create a session and shows the "Session cannot be started." message, I tried to investigate and it looks like the api endpoint used returns 404 from crunchyroll themselves, might need a new way to create a session/login

**Comment by matrss** [comment]
Same here. Queue, history and search were loading forever and logout/login lead to this session issue.

**Comment by nicolastoews** [comment]
Same here. I even tried reinstalling the app and nothing works

**Comment by mateussouzaweb** [comment]
The API is very old, so they probably put a end on it. I will see if we can found other API to migrate...

**Comment by matrss** [comment]
I have just taken a very short look, but I think CR-Unblocker has an auth endpoint that could still work (atleast it does not 404...):

https://github.com/fhuhne/CR-Unblocker/blob/6ac701ce825ee9a9589b552e5bcd2c36cf7e9f02/src/background.js#L3

**Comment by Kingdolor** [comment]
Same problem here. Can‘t start a session.

**Comment by Narcwis** [comment]
> The API is very old, so they probably put a end on it. I will see if we can found other API to migrate...

I was using the wrong request when I opened the issue, seems like we would need a new token, the api seems fine just gives this response:
```
{
    "error": true,
    "code": "bad_auth_params",
    "message": "Unauthenticated request"
}
```

**Comment by the4thstate** [comment]
Same here. I use it everyday, so really looking forward to a solution. Thanks in advance for your time!

**Comment by coolfizzin** [comment]
Yes, thank you!

**Comment by svenkraker** [comment]
Can't login anymore, same issue with no session. Been using this awesome app for a year and love it.

**Comment by hiki900** [comment]
Same problem guys. Looking forward for the solution and New version from the app.

**Comment by Hoffmeisters** [comment]
I think u can replace the `start_session` request for `https://api.crunchyroll.com/get_upsell_data.0.json?sess_id=1&device_id=whatvalueshouldbeforweb&device_type=com.crunchyroll.static&access_token=giKq5eY27ny3cqz&referer=https://www.crunchyroll.com/welcome/login`.
I made some kick tests and it seems to work just fine.

**Comment by sapkra** [comment]
Can't we maybe use the Device API to authenticate the webOS app? As far as I understood the other Apps like for fireTV are using this approach.

<img width="482" alt="image" src="https://github.com/mateussouzaweb/crunchyroll-webos/assets/8087568/2f78982e-a259-4ddc-b827-912a314928b5">

**Comment by mateussouzaweb** [comment]
Luckily someone did an amazing job of discovering the new API internals that is better and have many new features. I already made the initial implementation and login works (once you bypass CORS). 

It will be necessary to review everything and possibly change the system to adapt new features. It will take some time, but should be much more better!

**Comment by uherman** [comment]
> Luckily someone did an amazing job of discovering the new API internals that is better and have many new features - https://github.com/jhassan8/crunchyroll-tizen. I already made the initial implementation and login works (once you bypass CORS).
> 
> It will be necessary to review everything and possibly change the system to adapt new features. It will take some time, but should be much more better!

Does this mean that there is a working solution in the making for this project, or will [cruchyroll-tizen](https://github.com/jhassan8/crunchyroll-tizen) receive WebOS support?

**Comment by nicolastoews** [comment]
> > Luckily someone did an amazing job of discovering the new API internals that is better and have many new features - https://github.com/jhassan8/crunchyroll-tizen. I already made the initial implementation and login works (once you bypass CORS).
> > It will be necessary to review everything and possibly change the system to adapt new features. It will take some time, but should be much more better!
> 
> Does this mean that there is a working solution in the making for this project, or will [cruchyroll-tizen](https://github.com/jhassan8/crunchyroll-tizen) receive WebOS support?

It seems that project will support WebOS in the future
![image](https://github.com/mateussouzaweb/crunchyroll-webos/assets/98475310/9d90be31-c28c-4035-ac1d-2c1c0797f4ae)

**Comment by selectiveUk** [comment]
so whats the step for the minute does this mean we will be unable to watch crunchy roll via this app until an update is made ? or is there a way to get tizen on lgtv ?

**Comment by nicolastoews** [comment]
> so whats the step for the minute does this mean we will be unable to watch crunchy roll via this app until an update is made ? or is there a way to get tizen on lgtv ?

For now we'll need to wait to mateussouzaweb to fix this on an update or wait until the person who did it for Tizen finishes the WebOS compatibility

**Comment by KarmasTomb** [comment]
> I think u can replace the `start_session` request for `https://api.crunchyroll.com/get_upsell_data.0.json?sess_id=1&device_id=whatvalueshouldbeforweb&device_type=com.crunchyroll.static&access_token=giKq5eY27ny3cqz&referer=https://www.crunchyroll.com/welcome/login`. I made some quick tests and it seems to work just fine.
> 
> Source: https://github.com/yt-dlp/yt-dlp/blob/00a3e47bf5440c96025a76e08337ff2a475ed83e/yt_dlp/extractor/crunchyroll.py#L49

So I click on the website, copy the code, and paste it where start session would be?

**Comment by Nicolucaspro** [comment]
Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk
![IMG_20240113_171412](https://github.com/mateussouzaweb/crunchyroll-webos/assets/156543495/ec5a71bb-dedc-44f8-9d16-18131e58464c)

**Comment by KarmasTomb** [comment]
> Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk
> ![IMG_20240113_171412](https://github.com/mateussouzaweb/crunchyroll-webos/assets/156543495/ec5a71bb-dedc-44f8-9d16-18131e58464c)
> 

Awesome thank you! the link you sent, we download it onto the pc dev manager app for webos? :)

**Comment by SirH3nry** [comment]
> Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk ![IMG_20240113_171412](https://private-user-images.githubusercontent.com/156543495/296519729-ec5a71bb-dedc-44f8-9d16-18131e58464c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTEwMjMsIm5iZiI6MTcwNTE5MDcyMywicGF0aCI6Ii8xNTY1NDM0OTUvMjk2NTE5NzI5LWVjNWE3MWJiLWRlZGMtNDRmOC05ZDE2LTE4MTMxZTU4NDY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMDA1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGRmN2I1MjZjMGYwYmY4NWUxZDljNmY5NWRkMzA4MGExM2UwYzM2OWRkNmE2YzU1NDg1MTAzOTY2NGJhM2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8azB9_WnsT0rD6Zz2vaXr2UPxVFjZnvELFHZvSzVMqU)

Installed it just fine but the login screen just clears when I enter my information. How can we be sure this isn't a phish?

**Comment by Nicolucaspro** [comment]
> > Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk
> > ![IMG_20240113_171412](https://private-user-images.githubusercontent.com/156543495/296519729-ec5a71bb-dedc-44f8-9d16-18131e58464c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTM1NTQsIm5iZiI6MTcwNTE5MzI1NCwicGF0aCI6Ii8xNTY1NDM0OTUvMjk2NTE5NzI5LWVjNWE3MWJiLWRlZGMtNDRmOC05ZDE2LTE4MTMxZTU4NDY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMDQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGMwNDRmMjBkMTVmMWE2NDg1N2UxZjk0NjRiNzFkZjgwYzkxOTE3YTBhZjFlNzYwZDFhZmQ4YjE2MzY4ZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X4spasFhWoQM0gawzy_50vTwS6mAwtrag-2pv7PnpO0)
> 
> Awesome thank you! this works for webos?

If it works, it is a matter of once you have linked the TV with the Dev app, click on it in the folder that says Install

**Comment by Nicolucaspro** [comment]
> > Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk ![IMG_20240113_171412](https://private-user-images.githubusercontent.com/156543495/296519729-ec5a71bb-dedc-44f8-9d16-18131e58464c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTEwMjMsIm5iZiI6MTcwNTE5MDcyMywicGF0aCI6Ii8xNTY1NDM0OTUvMjk2NTE5NzI5LWVjNWE3MWJiLWRlZGMtNDRmOC05ZDE2LTE4MTMxZTU4NDY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMDA1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGRmN2I1MjZjMGYwYmY4NWUxZDljNmY5NWRkMzA4MGExM2UwYzM2OWRkNmE2YzU1NDg1MTAzOTY2NGJhM2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8azB9_WnsT0rD6Zz2vaXr2UPxVFjZnvELFHZvSzVMqU)
> 
> Installed it just fine but the login screen just clears when I enter my information.

It's not very difficult bro these days I will put together the tutorial but what you should do at that login is click on the checkbox that you have finished writing and click on the button below to go to the password and that way you can start in a way simple within the app everything is very renewed

**Comment by sapkra** [comment]
> > Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk ![IMG_20240113_171412](https://private-user-images.githubusercontent.com/156543495/296519729-ec5a71bb-dedc-44f8-9d16-18131e58464c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTEwMjMsIm5iZiI6MTcwNTE5MDcyMywicGF0aCI6Ii8xNTY1NDM0OTUvMjk2NTE5NzI5LWVjNWE3MWJiLWRlZGMtNDRmOC05ZDE2LTE4MTMxZTU4NDY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMDA1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGRmN2I1MjZjMGYwYmY4NWUxZDljNmY5NWRkMzA4MGExM2UwYzM2OWRkNmE2YzU1NDg1MTAzOTY2NGJhM2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8azB9_WnsT0rD6Zz2vaXr2UPxVFjZnvELFHZvSzVMqU)
> 
> Installed it just fine but the login screen just clears when I enter my information.

Had the same problem, then I double clicked into the input fields, so that the native keyboard appeared. This one worked fine, but the in-app keyboard did not.

**Comment by Nicolucaspro** [comment]
> > > Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk ![IMG_20240113_171412](https://private-user-images.githubusercontent.com/156543495/296519729-ec5a71bb-dedc-44f8-9d16-18131e58464c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTEwMjMsIm5iZiI6MTcwNTE5MDcyMywicGF0aCI6Ii8xNTY1NDM0OTUvMjk2NTE5NzI5LWVjNWE3MWJiLWRlZGMtNDRmOC05ZDE2LTE4MTMxZTU4NDY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMDA1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGRmN2I1MjZjMGYwYmY4NWUxZDljNmY5NWRkMzA4MGExM2UwYzM2OWRkNmE2YzU1NDg1MTAzOTY2NGJhM2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8azB9_WnsT0rD6Zz2vaXr2UPxVFjZnvELFHZvSzVMqU)
> > 
> > 
> > Installed it just fine but the login screen just clears when I enter my information.
> 
> Had the same problem, then I double clicked into the input fields, so that the native keyboard appeared. This one worked fine, but the in-app keyboard did not.

Just in case I will inform the creator so that he is aware of the issue regarding that keyboard issue but in my case it worked very well, I noticed other bugs in this regard but the author is already working on solving them

**Comment by sapkra** [comment]
@Nicolucaspro Maybe it was a different problem but it appeared to me like that. The second try to login worked and it was the only thing i did differently.

**Comment by Nicolucaspro** [comment]
> @Nicolucaspro Maybe it was a different problem but it appeared to me like that. The second try to login worked and it was the only thing i did differently.

@sapkra I understand, I hope you enjoy your experience in the app but keep in mind that it is under constant development by the creator

**Comment by KarmasTomb** [comment]
> > > Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk
> > > ![IMG_20240113_171412](https://private-user-images.githubusercontent.com/156543495/296519729-ec5a71bb-dedc-44f8-9d16-18131e58464c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTM1NTQsIm5iZiI6MTcwNTE5MzI1NCwicGF0aCI6Ii8xNTY1NDM0OTUvMjk2NTE5NzI5LWVjNWE3MWJiLWRlZGMtNDRmOC05ZDE2LTE4MTMxZTU4NDY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMDQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGMwNDRmMjBkMTVmMWE2NDg1N2UxZjk0NjRiNzFkZjgwYzkxOTE3YTBhZjFlNzYwZDFhZmQ4YjE2MzY4ZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X4spasFhWoQM0gawzy_50vTwS6mAwtrag-2pv7PnpO0)
> > 
> > Awesome thank you! this works for webos?
> 
> If it works, it is a matter of once you have linked the TV with the Dev app, click on it in the folder that says Install

worked just fine! thank you, I appreciate it! ![20240113_170506.jpg](https://github.com/mateussouzaweb/crunchyroll-webos/assets/124021309/277a59a2-7121-49a1-96b0-aa9948d78bab)

**Comment by Nicolucaspro** [comment]
> > > > Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk
> > > > ![IMG_20240113_171412](https://private-user-images.githubusercontent.com/156543495/296519729-ec5a71bb-dedc-44f8-9d16-18131e58464c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTM1NTQsIm5iZiI6MTcwNTE5MzI1NCwicGF0aCI6Ii8xNTY1NDM0OTUvMjk2NTE5NzI5LWVjNWE3MWJiLWRlZGMtNDRmOC05ZDE2LTE4MTMxZTU4NDY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMDQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGMwNDRmMjBkMTVmMWE2NDg1N2UxZjk0NjRiNzFkZjgwYzkxOTE3YTBhZjFlNzYwZDFhZmQ4YjE2MzY4ZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X4spasFhWoQM0gawzy_50vTwS6mAwtrag-2pv7PnpO0)
> > > 
> > > 
> > > Awesome thank you! this works for webos?
> > 
> > 
> > If it works, it is a matter of once you have linked the TV with the Dev app, click on it in the folder that says Install
> 
> worked just fine! thank you, I appreciate it! ![20240113_170506.jpg](https://private-user-images.githubusercontent.com/124021309/296524518-277a59a2-7121-49a1-96b0-aa9948d78bab.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMDAwODYsIm5iZiI6MTcwNTE5OTc4NiwicGF0aCI6Ii8xMjQwMjEzMDkvMjk2NTI0NTE4LTI3N2E1OWEyLTcxMjEtNDlhMS05NmIwLWFhOTk0OGQ3OGJhYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMjM2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTM1Zjk4MjM2NjE2MzgyZjc0Njk2NThmZDFlZTM4Y2YzNjY2MGE4MjY3Yzk2ZjdmZWQ3YTFiMzEzZGJlMTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M3dtbQedQnXfHGVb3UaFAY2u2kiIlCSylVyjh9GHmCE)

@KarmasTomb Don't thank me, I deeply thank the creator for bringing this app, it works quite well and has a very renewed interface, I hope you enjoy it.

**Comment by Nicolucaspro** [comment]
> > > > Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk
> > > > ![IMG_20240113_171412](https://private-user-images.githubusercontent.com/156543495/296519729-ec5a71bb-dedc-44f8-9d16-18131e58464c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTM1NTQsIm5iZiI6MTcwNTE5MzI1NCwicGF0aCI6Ii8xNTY1NDM0OTUvMjk2NTE5NzI5LWVjNWE3MWJiLWRlZGMtNDRmOC05ZDE2LTE4MTMxZTU4NDY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMDQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGMwNDRmMjBkMTVmMWE2NDg1N2UxZjk0NjRiNzFkZjgwYzkxOTE3YTBhZjFlNzYwZDFhZmQ4YjE2MzY4ZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X4spasFhWoQM0gawzy_50vTwS6mAwtrag-2pv7PnpO0)
> > > 
> > > 
> > > Awesome thank you! this works for webos?
> > 
> > 
> > If it works, it is a matter of once you have linked the TV with the Dev app, click on it in the folder that says Install
> 
> worked just fine! thank you, I appreciate it! ![20240113_170506.jpg](https://private-user-images.githubusercontent.com/124021309/296524518-277a59a2-7121-49a1-96b0-aa9948d78bab.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMDAwODYsIm5iZiI6MTcwNTE5OTc4NiwicGF0aCI6Ii8xMjQwMjEzMDkvMjk2NTI0NTE4LTI3N2E1OWEyLTcxMjEtNDlhMS05NmIwLWFhOTk0OGQ3OGJhYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMjM2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTM1Zjk4MjM2NjE2MzgyZjc0Njk2NThmZDFlZTM4Y2YzNjY2MGE4MjY3Yzk2ZjdmZWQ3YTFiMzEzZGJlMTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M3dtbQedQnXfHGVb3UaFAY2u2kiIlCSylVyjh9GHmCE)

@KarmasTomb Don't thank me, I deeply thank the creator for bringing this app, it works quite well and has a very renewed interface, I hope you enjoy it as much as I have tried it so far.

**Comment by afarah1** [comment]
> > > Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk
> > > ![IMG_20240113_171412](https://private-user-images.githubusercontent.com/156543495/296519729-ec5a71bb-dedc-44f8-9d16-18131e58464c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTM1NTQsIm5iZiI6MTcwNTE5MzI1NCwicGF0aCI6Ii8xNTY1NDM0OTUvMjk2NTE5NzI5LWVjNWE3MWJiLWRlZGMtNDRmOC05ZDE2LTE4MTMxZTU4NDY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMDQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGMwNDRmMjBkMTVmMWE2NDg1N2UxZjk0NjRiNzFkZjgwYzkxOTE3YTBhZjFlNzYwZDFhZmQ4YjE2MzY4ZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X4spasFhWoQM0gawzy_50vTwS6mAwtrag-2pv7PnpO0)
> > 
> > 
> > Awesome thank you! this works for webos?
> 
> If it works, it is a matter of once you have linked the TV with the Dev app, click on it in the folder that says Install

I get "Type error" when trying to install from desktop dev manager. No one else had that?

**Comment by Nicolucaspro** [comment]
> > > > Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk
> > > > ![IMG_20240113_171412](https://private-user-images.githubusercontent.com/156543495/296519729-ec5a71bb-dedc-44f8-9d16-18131e58464c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTM1NTQsIm5iZiI6MTcwNTE5MzI1NCwicGF0aCI6Ii8xNTY1NDM0OTUvMjk2NTE5NzI5LWVjNWE3MWJiLWRlZGMtNDRmOC05ZDE2LTE4MTMxZTU4NDY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwMDQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGMwNDRmMjBkMTVmMWE2NDg1N2UxZjk0NjRiNzFkZjgwYzkxOTE3YTBhZjFlNzYwZDFhZmQ4YjE2MzY4ZmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X4spasFhWoQM0gawzy_50vTwS6mAwtrag-2pv7PnpO0)
> > > 
> > > 
> > > Awesome thank you! this works for webos?
> > 
> > 
> > If it works, it is a matter of once you have linked the TV with the Dev app, click on it in the folder that says Install
> 
> I get "Type error" when trying to install from desktop dev manager. No one else had that?

This is not my case, it must be a procedural error but I will soon make a tutorial on how to do it.

**Comment by Juanhulk21** [comment]
> Now there is a new app that allows you to use Crunchyroll without this error. It is from the same author as the Tizen version and I have already tried it. The author will continue to support it and is from the Latin community (like me) but everything is in English for ease. universal to install it you need Web OS Dev https://github.com/jhassan8/crunchyroll-tizen/blob/feature/webos/com.difix.crunchyroll_1.0.0_all.ipk ![IMG_20240113_171412](https://private-user-images.gith)

worked just fine! thank you!
