### ISSUE TITLE
Unable to go to next episode

### ISSUE THREAD

**Issue by vinismarques** [mateussouzaweb/crunchyroll-webos#35]
Hi there! Thank for you work on this great app!

I'm having issues when trying to go to the next episode when I finish the current one. I tried clicking both on the next button on the top right corner and on the "skip" on the bottom of the ui, none of which worked. When clicking on the top right button, it seems like it is loading the next ep, but then the same episode is loaded and continued from the same part you were watching before clicking the button.

**Comment by mateussouzaweb** [comment]
@vinismarques I will look at this, but a bit more context will be helpful... please provide more details:

Do you watch episodes in what audio language?
Do you watch episodes with what subtitles?
What anime/season/episode are you trying to watch?

**Comment by vinismarques** [comment]
Thank you for the prompt response.

Sure! The issue seems to happen in all anime/episodes that I tested, but here is one of the latest ones: Solo Leveling, 1st season, episode 1, original audio, and with Portuguese subtitles.

**Comment by mateussouzaweb** [comment]
@vinismarques this bug has been fixed in the new app version. Can you test?

**Comment by vinismarques** [comment]
Fixed! Thank you for it.
