### ISSUE TITLE
Anime with 20+ eps

### ISSUE THREAD

**Issue by YoshikTK** [mateussouzaweb/crunchyroll-webos#6]
Hi,
I just started using Your app now on Lg CX. It is good alternative to original, few things added would be great but for now the question is how to choose a specific ep when anime have multiple seasons, a lot of eps. For example Attack on titan I can or see first 19 ep or last 19, depending will i choose desc or asc option.
Anyway to expand the list over 19?
Thanks
Tom

**Comment by mateussouzaweb** [comment]
Thanks for the feedback. I just released a new version with pagination on serie episodes.  Please check if that works for you.

**Comment by YoshikTK** [comment]
Thanks, work great.
Just one more question, would be possible to add "next episode" button?

**Comment by mateussouzaweb** [comment]
@YoshikTK that feature is in the roadmap. Too bad that API does not provide a call for this, but I been thinking a way and believe it will work.
