### ISSUE TITLE
make build not working for me

### ISSUE THREAD

**Issue by Eric-Lui** [mateussouzaweb/crunchyroll-webos#7]
Hi, I was trying to install the app using your instructions but got stuck after cloning the repository. I am a bit new to programming and would appreciate if you can tell me what I am doing wrong. I was trying to make build after cloning the repository in the webOS TV CLI but would get a message saying that 'make' is not recognized as a command even though I see the Makefile and everything cloned correctly in the folder.

**Comment by mateussouzaweb** [comment]
You need to install the build tool in the OS. On Ubuntu based distros, use:

```sudo apt-get install build-essential```

Also, please be aware of the project depends on https://github.com/mateussouzaweb/compactor to build from ``src/`` and the version that I am using is not available yet. But you can build it with webpack, parcel or anything else...
