### ISSUE TITLE
No Content appaering on webOS TV Version: 3.9.0-62905

### ISSUE THREAD

**Issue by amine-amari** [mateussouzaweb/crunchyroll-webos#8]
Hello Mateus,
Thank you for developping this app, I really appreciate it.
I tested the following [Link](https://mateussouzaweb.com/tv) on an LG TV with webOS TV Version: 3.9.0-62905
There was no login request and no content is appearing (see Attachment).

**Comment by mateussouzaweb** [comment]
@amine-amari the app only works with WebOS version 4.0+ because of internal JavaScript engine.
See if there is a way of upgrade your TV.
